/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pkg2labo_mpwt.conexion;
import pkg2labo_mpwt.query_mpwt;

/**
 *
 * @author Alejandro
 */
public class JIFrame_equipos extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame2
     */
    DefaultTableModel model;
    conexion cn;
    query_mpwt query;
    public JIFrame_equipos() throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {
        initComponents();
        cn =  new conexion();
        query = new query_mpwt();
        this.cargar();
    }
    public void cargar(){
        ResultSet rs = null;
        try {
            DefaultTableModel model = new DefaultTableModel();
            String[] nombreColum = {"Código", "Nombre"};
            model.setColumnIdentifiers(nombreColum);
//            mpwt_conexion conex = new mpwt_conexion("jdbc:mysql://localhost:3306/clase08", "root", "");

            rs = cn.query(query.equipos());
            String nombre;
            int codigo;

            while (rs.next()) {
                codigo = rs.getInt("codigo");
                nombre = rs.getString("nombre");
                model.addRow(new Object[]{codigo, nombre});
            }
            this.jTable1.setModel(model);
            this.jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            this.jTable1.setFillsViewportHeight(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    public void limpiar(){
        this.jtCod.setText("");
        this.jtNombre.setText("");
        this.jbAgg.setEnabled(true);
        this.jtCod.setEditable(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtCod = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jbAgg = new javax.swing.JButton();
        jbMod = new javax.swing.JButton();
        JbElim = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Equipo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta Teams");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Código del equipo:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nombre del equipo:");

        jtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodActionPerformed(evt);
            }
        });

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jbAgg.setBackground(new java.awt.Color(0, 102, 0));
        jbAgg.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jbAgg.setForeground(new java.awt.Color(255, 255, 255));
        jbAgg.setText("Agregar");
        jbAgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAggActionPerformed(evt);
            }
        });

        jbMod.setBackground(new java.awt.Color(0, 0, 153));
        jbMod.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jbMod.setForeground(new java.awt.Color(255, 255, 255));
        jbMod.setText("Modificar");
        jbMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModActionPerformed(evt);
            }
        });

        JbElim.setBackground(new java.awt.Color(153, 0, 0));
        JbElim.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        JbElim.setForeground(new java.awt.Color(255, 255, 255));
        JbElim.setText("Eliminar");
        JbElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbElimActionPerformed(evt);
            }
        });

        jButton_limpiar.setBackground(new java.awt.Color(153, 0, 0));
        jButton_limpiar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_limpiar.setText("Limpiar");
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(257, 257, 257))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_limpiar)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbAgg)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbMod)
                                        .addGap(18, 18, 18)
                                        .addComponent(JbElim))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbAgg)
                        .addComponent(jbMod)
                        .addComponent(JbElim)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_limpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodActionPerformed

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jbAggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAggActionPerformed
        if(this.jtCod.getText().trim().equals("") || this.jtNombre.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe agregar información en los campos.");
        }
        else{
            try {
            String sqlInsert = query.ingresar_equipo(Integer.parseInt(this.jtCod.getText()), this.jtNombre.getText().trim().toUpperCase());
            cn.query_ingreso_actu_elim(sqlInsert);
            this.cargar();
            this.limpiar();
            } catch (SQLException ex) {
                Logger.getLogger(JIFrame_equipos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }       
    }//GEN-LAST:event_jbAggActionPerformed

    private void jbModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModActionPerformed
        if (this.jTable1.getSelectedRow() != -1)
        {
            if (this.jtCod.getText().trim().equals("") || this.jtNombre.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe agregar información en los campos.");
            }
            else{
                try {
                    String sqlUpdate = query.actu_equipo(Integer.parseInt(this.jtCod.getText()), this.jtNombre.getText().trim().toUpperCase());
                    cn.query_ingreso_actu_elim(sqlUpdate);
                    this.cargar();
                    this.limpiar();
                } catch (SQLException ex) {
                    Logger.getLogger(JIFrame_equipos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }   
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe selecionar un registro.");
        }
        
    }//GEN-LAST:event_jbModActionPerformed

    private void JbElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbElimActionPerformed
        if (this.jTable1.getSelectedRow() != -1){
            try {
                String sqlDelete = query.eliminar_equipo(Integer.parseInt(this.jtCod.getText()));
                cn.query_ingreso_actu_elim(sqlDelete);
                this.cargar();
                this.limpiar();
            } catch (SQLException ex) {
                Logger.getLogger(JIFrame_equipos.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         else{
            JOptionPane.showMessageDialog(null, "Debe selecionar un registro.");
        }
       
    }//GEN-LAST:event_JbElimActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        this.jbAgg.setEnabled(false);
        this.jtCod.setEditable(false);
        int index = this.jTable1.getSelectedRow();
        this.jtCod.setText(((DefaultTableModel)this.jTable1.getModel()).getValueAt(index, 0).toString());
        this.jtNombre.setText(((DefaultTableModel)this.jTable1.getModel()).getValueAt(index, 1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jButton_limpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbElim;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAgg;
    private javax.swing.JButton jbMod;
    private javax.swing.JTextField jtCod;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
