/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pkg2labo_mpwt.conexion;
import pkg2labo_mpwt.query_mpwt;

/**
 *
 * @author Alejandro
 */
public class NewJInternalFrame_ingreso_universidad extends javax.swing.JInternalFrame {

    query_mpwt consulta;
    ResultSet rs;
    conexion conex;
    DefaultTableModel model;
    public NewJInternalFrame_ingreso_universidad() throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {
        initComponents();
        consulta = new query_mpwt();
        conex = new conexion();
        model = new DefaultTableModel();
        this.cargar();
    }
    public void cargar() {
        try {
            this.model.setNumRows(0);
            String[] nombreColum = {"id_universidad", "Nombre"};
            model.setColumnIdentifiers(nombreColum);
            rs = conex.query(consulta.mostrar_universidad());
            String id_univer, nombre;
            while (rs.next()) {
                id_univer = rs.getString("id_universidad");
                nombre = rs.getString("nombre");
                model.addRow(new Object[]{id_univer, nombre});
            }
            this.jTable1.setModel(model);
            this.jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            this.jTable1.setFillsViewportHeight(true);
            
        } catch (Exception e) {
        }    
    }
    public void limpiar(){
        this.jTextField_universidad.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_universidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_agregar_uni = new javax.swing.JButton();
        jButton_modificar = new javax.swing.JButton();
        jButton_eleminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Universidad");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Nombre de la universidad");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton_agregar_uni.setBackground(new java.awt.Color(0, 102, 0));
        jButton_agregar_uni.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton_agregar_uni.setForeground(new java.awt.Color(255, 255, 255));
        jButton_agregar_uni.setText("Agregar");
        jButton_agregar_uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregar_uniActionPerformed(evt);
            }
        });

        jButton_modificar.setBackground(new java.awt.Color(0, 0, 102));
        jButton_modificar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_modificar.setText("Modificar");
        jButton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificarActionPerformed(evt);
            }
        });

        jButton_eleminar.setBackground(new java.awt.Color(153, 0, 0));
        jButton_eleminar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton_eleminar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_eleminar.setText("Eliminar");
        jButton_eleminar.setToolTipText("");
        jButton_eleminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eleminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_universidad, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_agregar_uni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButton_eleminar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_universidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_agregar_uni)
                    .addComponent(jButton_modificar)
                    .addComponent(jButton_eleminar))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_agregar_uniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregar_uniActionPerformed
        String universidad;  
        if (this.jTextField_universidad.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Error! Debe ingresar un nombre");
        }
        else{
            try {
                universidad = this.jTextField_universidad.getText().trim().toUpperCase();

                conex.query_ingreso_actu_elim(consulta.ingresar_univer(universidad));
                this.cargar();
                this.limpiar();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_jButton_agregar_uniActionPerformed

    private void jButton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modificarActionPerformed
        String universidad, id_unive;
        
        if (this.jTable1.getSelectedRow() > -1) {
            if (this.jTextField_universidad.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Error! Debe ingresar un nombre");
            }
            else{
                try {
                    id_unive = String.valueOf(this.model.getValueAt(this.jTable1.getSelectedRow(), 0));
                    int id = Integer.parseInt(id_unive);
                    universidad = this.jTextField_universidad.getText().trim().toUpperCase();
                    conex.query_ingreso_actu_elim(consulta.modificar_univer(id, universidad));

                    this.cargar();
                    this.limpiar();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e.toString());
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Error! Debe elegir un dato de la lista");
        }
    }//GEN-LAST:event_jButton_modificarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String univer = String.valueOf(model.getValueAt(jTable1.getSelectedRow(), 1));
        this.jTextField_universidad.setText(univer);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_eleminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eleminarActionPerformed
        String id_unive;
        if (this.jTable1.getSelectedRow() > -1) {
            try {
                id_unive = String.valueOf(this.model.getValueAt(this.jTable1.getSelectedRow(), 0));
                int id = Integer.parseInt(id_unive);
                conex.query_ingreso_actu_elim(consulta.eliminar_universidad(id));
                this.cargar();
                this.limpiar();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error! La universidad seleccionada ya contiene relaciones");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Error! Debe elegir un dato de la lista");
        }
    }//GEN-LAST:event_jButton_eleminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_agregar_uni;
    private javax.swing.JButton jButton_eleminar;
    private javax.swing.JButton jButton_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_universidad;
    // End of variables declaration//GEN-END:variables
}
